apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: secure-eks-cluster
  region: us-east-1

vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: false

managedNodeGroups:
  - name: secure-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: true

cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
